string current_specialization_demon_hero_3_bonus
{
	Text( return, "1" )
}

//

string current_specialization_demon_hero_5_spec_bonus
{
	Text( return, "40" )
}

string current_specialization_demon_hero_5_spec_bonus_alt
{
	Text( return, "2" )
}

string current_specialization_demon_hero_5_spec_increment
{
	Text( return, "5" )
}

string current_specialization_demon_hero_5_spec_level_step
{
	Text( return, "3" )
}

//

string current_specialization_demon_hero_6_spec_bonus
{
	Text( return, "4" )
}

string current_specialization_demon_hero_6_spec_increment
{
	Text( return, "1" )
}

string current_specialization_demon_hero_6_spec_level_step
{
	Text( return, "2" )
}