string current_sub_class_human_might_1
{
	Text( return, "200" )
}

string current_sub_class_human_magic_2
{
	Text( return, "0" )
}

string current_sub_class_unfrozen_magic_1
{
	Text( return, "10" )
}

string current_sub_class_demons_magic_1
{
	Text( return, "200" )
}

string current_sub_class_demons_magic_2
{
	Text( return, "5" )
}

string current_sub_class_dungeon_might_1
{
	Text( return, "100" )
}

string current_sub_class_dungeon_might_2
{
	Text( return, "100" )
}

string current_sub_class_dungeon_magic_1
{
	Text( return, "100" )
}

string current_sub_class_dungeon_magic_2
{
	Text( return, "10000" )
}