string current_map_object_mine_param_1
{ 
	Text( return, "2" )
}

string current_map_object_mine_param_2
{ 
	Text( return, "1" )
}

string current_map_object_mine_param_3
{ 
	Text( return, "1000" )
}


string current_map_object_storage_param_1
{ 
	Text( return, "6-10" )
}

string current_map_object_storage_param_2
{ 
	Text( return, "3-5" )
}

string current_map_object_storage_param_3
{ 
	Text( return, "2500-3500" )
}

string current_map_object_storage_param_4
{ 
	Text( return, "20-40" )
}


string current_map_object_resource_param_1
{ 
	Text( return, "400-800" )
}

string current_map_object_resource_param_2
{ 
	Text( return, "5-8" )
}

string current_map_object_resource_param_3
{ 
	Text( return, "3-5" )
}

string current_map_object_resource_param_4
{ 
	Text( return, "8-12" )
}


string current_map_object_chest_param_1
{ 
	Text( return, "1000-2000" )
}

string current_map_object_chest_param_2
{ 
	Text( return, "2000" )
}


string current_map_object_celestial_sphere_param
{ 
	Text( return, "1" )
}

string current_map_object_lost_library_param
{ 
	Text( return, "6000-10000" )
}

string current_map_object_hero_stats_param_1
{ 
	Text( return, "1" )
}

string current_map_object_hero_stats_param_2
{ 
	Text( return, "2" )
}

string current_map_object_hero_stats_param_2_cost
{ 
	Text( return, "1000" )
}

string current_map_object_maze_param
{ 
	Text( return, "2" )
}

string current_map_object_trial_scales_param
{ 
	Text( return, "4" )
}

string current_map_object_college_of_wonder_param
{ 
	Text( return, "1" )
}

string current_map_object_college_of_wonder_param_cost
{ 
	Text( return, "5000" )
}

string current_map_object_hero_buff_param
{ 
	Text( return, "3" )
}

string current_map_object_pile_of_books_param
{ 
	Text( return, "25" )
}

string current_map_object_mysterious_stone_param
{ 
	Text( return, "50" )
}

string current_map_object_temple_of_magic_param
{ 
	Text( return, "1" )
}

string current_map_object_altar_of_magic_param_1
{ 
	Text( return, "1" )
}

string current_map_object_altar_of_magic_param_2
{ 
	Text( return, "3" )
}

string current_map_object_university_param_1
{ 
	Text( return, "4" )
}

string current_map_object_university_param_2
{ 
	Text( return, "2500" )
}

string current_map_object_mystical_tower_param
{ 
	Text( return, "4" )
}

string current_map_object_huntsmans_camp_param
{ 
	Text( return, "50" )
}

string current_map_object_huntsmans_camp_param_1
{ 
	Text( return, "50" )
}

string current_map_object_stables_param
{ 
	Text( return, "20" )
}

string current_map_object_fountain_param
{ 
	Text( return, "40" )
}

string current_map_object_learning_stone_param
{ 
	Text( return, "1000" )
}

string current_map_object_insaras_eye_param
{ 
	Text( return, "250" )
}

string current_map_object_monty_hall_param_1
{ 
	Text( return, "1" )
}

string current_map_object_monty_hall_param_2
{ 
	Text( return, "3" )
}

string current_map_object_random_hire_param
{ 
	Text( return, "3" )
}

string current_map_object_hire_param
{ 
	Text( return, "1" )
}

string current_map_insaras_eye_param
{ 
	Text( return, "250" )
}